import { Inter, Roboto, Dancing_Script } from "next/font/google";
import "./globals.css";
import "@uploadthing/react/styles.css";
import ReduxProvider from "../redux/provider";

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200"],
  variable: "--font-inter",
});
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  variable: "--font-roboto",
});
const dancing_script = Dancing_Script({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-dancing_script",
});

export const metadata = {
  title: "Online Shoping Store for all products",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${roboto.variable} ${dancing_script.variable}`}
      >
        <ReduxProvider> {children} </ReduxProvider>
      </body>
    </html>
  );
}
